version: '2'

services:

    nginx:
        build: ./.docker/nginx/
        ports:
            - 80:80
        volumes:
            - ./:/code
            - ./.docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
            - ./.docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/nginx/log:/var/log/nginx
        links:
            - php:php

    php:
        build: ./.docker/php/
        ports:
            - 9000:9000
        volumes:
            - ./:/code
            - ./.docker/php/config/php.ini:/usr/local/etc/php/php.ini
        links:
            - mysql:mysql
            - redis:redis
               
    mysql:
        build: ./.docker/mysql/
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: nette
            MYSQL_USER: nette
            MYSQL_PASSWORD: nette
            
    redis:
        build: ./.docker/redis/
        ports:
            - 6379:6379
        volumes:
            - ./.docker/redis/config/redis.conf:/usr/local/etc/redis/redis.conf